services:
  backend:
    image: app-service:latest
    ports: 
      - 8080:8080
  frontend:
    image: app-frontend:latest
    ports: 
      - 4200:4200
    environment:
      - API_URL=http://backend:8080
  